### PR TITLE
feat: Support user-defined refresh time

### PR DESCRIPTION
**Pull request by changyl**
Users are more flexible in refreshing data without having to wait for the framework to trigger a refresh

### CODE REVIEW

**Comment by lesismal** [comment]
The `nbio.Conn.flush` should be called when there's data waiting to be sent for the reason of `tcp send queue is full`.
Users don't know when the fd is writable, and the framework will `flush automatically once the fd becomes writable, so, users don't need to do it themself, and users calling for it would be a waste.

**Comment by lesismal** [comment]
It's totally different from `bufio.Writer.Flush`.

**Comment by changyl** [comment]
This approach is useful when the framework is used by middleware, which uses an asynchronous model for front-end connections while the back-end connections are still synchronous.

**Comment by changyl** [comment]
For example, if the backend connection returns a result, I need to block waiting for the result to be read, and when the result set is large, I collect part of the result set and can proactively send it to the front-end client

**Comment by lesismal** [comment]
I think you are misunderstanding how this `flush` works :smiley:

**Comment by lesismal** [comment]
Usually, `nbioConn.Write` write data directely, does not cache the data like `bufio.Writer` and no need to flush. 
Only when tcp send queue is full, the data is cached and wait for writable event, then to write the data again. And please notice that, the framework will just write the cached data directely as soon as the fd becomes writable again. So users don't need to handle the write event themselves. 

That's why I said "It's totally different from bufio.Writer.Flush".

**Comment by changyl** [comment]
Haha, nbioConn.Write is equivalent to io.Write and does not require flush. But isn't there another function of flush to free up memory pools? Large result sets that are not released in a timely manner are also a problem

**Comment by lesismal** [comment]
> Haha, nbioConn.Write is equivalent to io.Write and does not require flush. But isn't there another function of flush to free up memory pools? Large result sets that are not released in a timely manner are also a problem

Please read my explanation and it's better if you read the code too, make sure you have understood how it works first.
Else when your opinions are based on wrong knowledge, I'm not able to explain more 😃

**Comment by changyl** [comment]
I don't think you understand what I mean, if the amount of data in the nbio framework calling Write() causes the memory pool to swell, you can see the screenshot below.
image

**Comment by changyl** [comment]
I don't think you understand what I mean, if the amount of data in the nbio framework calling Write() causes the memory pool to swell, you can see the screenshot below.
image

**Comment by lesismal** [comment]
> Have you read the code related `nbio.Conn.flush()`? Can you explain what happens if users call `nbio.Conn.flush()` themselves?

Coz I really don't understand how your `flush` way can optimize the mem cost, if you can explain it more clearly, would help me to understand what you mean.

**Comment by lesismal** [comment]
Hi @changyl , I will close this pr since there isn't a further explanation.
Can open it again if you are sure it will work better.
Thanks for your feedback!

**Pull request closed without merging**
