### PR TITLE
auto expand the monitor events

### PR DESCRIPTION
**Pull request by sunvim**
awesome project, do you think about linear allocate algorithm to manage memory pool?

and i want to implement the gateway with this project, do you have any questions ?

### CODE REVIEW

**Comment by lesismal** [comment]
> awesome project, do you think about linear allocate algorithm to manage memory pool?

Do you mean 2^N like bytebufferpool? It's not suitable for http/ws on this or other poller like frameworks:

fasthttp serves each conn with one goroutine, the read/write in the same goroutine for loop, sync read/write one by one, so the buffer's size is easy to decide and the life cycle is easy to manage. 

But for poller frameworks, both read and write are async, and parsing/handling should be in different goroutines(usually, read+parsing in poller goroutines, message handling in application-layer goroutine pool). We always use the buffers between different layers such as tcp, tls, http and ws. the 2^N buffers can not be reused effectively enough. For async read and streaming parsing, we're not sure about the buffer size, and the buffer may be passed from a goroutine to another, and we need to handle half-packet problem, we may need more operations about copy and cache. Considering all of these, it's more difficult to manage the life cycle of buffers with 2^N. In fact, I use 2^N at the beginning which leads to a bad performance, so I change it to the pool like now.

**Comment by lesismal** [comment]
> > awesome project, do you think about linear allocate algorithm to manage memory pool?
> 
> Do you mean 2^N like bytebufferpool? It's not suitable for http/ws on this or other poller like frameworks:
> 
> fasthttp serves each conn with one goroutine, the read/write in the same goroutine for loop, sync read/write one by one, so the buffer's size is easy to decide and the life cycle is easy to manage.
> 
> But for poller frameworks, both read and write are async, and parsing/handling should be in different goroutines(usually, read+parsing in poller goroutines, message handling in application-layer goroutine pool). We always use the buffers between different layers such as tcp, tls, http and ws. the 2^N buffers can not be reused effectively enough. For async read and streaming parsing, we're not sure about the buffer size, and the buffer may be passed from a goroutine to another, and we need to handle half-packet problem, we may need more operations about copy and cache. Considering all of these, it's more difficult to manage the life cycle of buffers with 2^N. In fact, I use 2^N at the beginning which leads to a bad performance, so I change it to the pool like now.

英文解释比较吃力，之前有在其他地方解释过一些：
异步库的方案，对比标准库一连接一协程的方案，存在一个连接数的阈值，并不是异步库一定就性能优势，异步库的优势主要是降低内存占用、超大并发情况下的优势，单就10k，可能标准库的响应速度更快，因为数据的读取、解析没有断层、都是单协程内完成的、同一段buffer也可以复用很多次。单就内存优化来讲，比如内存池：
fasthttp等项目开了个pool的好头，但是对于异步网络库高度定制内存管理等场景，不够通用。
标准库方案的那种一个连接一个协程，就单个连接而言，在内存管理、pool定制上比异步库更方便，buffer多是在单个协程内、处理完一个消息后才会进行下一轮ReadMessage，所以内存管理更可控，异步库内存生命周期管理起来比一个连接一个协程麻烦太多了。
简单定制的tcp、固定header 那种要省力得多，tls/http/websocket解析起来太麻烦了，跨协议栈不同层之间的数据传递和cache，尤其是慢连接，比如测试解析逻辑时一个字节一个字节发送，再加上可能跨协程的buffer传递，还有解析到一个协议包后之前整段buffer的分割之后还需要粘包和cache等问题，结合2^N的pool的方案在应对慢连接时大部分性能都消耗在内存的使用上了，反倒性能不好。所以最近把http/websocket的内存池改了，不在使用的2^N对齐的buffer，换成无固定长度buffer的方式了，不保证一对一的分配和释放，只是尽量在各个协议层复用pool中的buffer

**Comment by sunvim** [comment]
> > > awesome project, do you think about linear allocate algorithm to manage memory pool?
> > 
> > 
> > Do you mean 2^N like bytebufferpool? It's not suitable for http/ws on this or other poller like frameworks:
> > fasthttp serves each conn with one goroutine, the read/write in the same goroutine for loop, sync read/write one by one, so the buffer's size is easy to decide and the life cycle is easy to manage.
> > But for poller frameworks, both read and write are async, and parsing/handling should be in different goroutines(usually, read+parsing in poller goroutines, message handling in application-layer goroutine pool). We always use the buffers between different layers such as tcp, tls, http and ws. the 2^N buffers can not be reused effectively enough. For async read and streaming parsing, we're not sure about the buffer size, and the buffer may be passed from a goroutine to another, and we need to handle half-packet problem, we may need more operations about copy and cache. Considering all of these, it's more difficult to manage the life cycle of buffers with 2^N. In fact, I use 2^N at the beginning which leads to a bad performance, so I change it to the pool like now.
> 
> 英文解释比较吃力，之前有在其他地方解释过一些：
> 异步库的方案，对比标准库一连接一协程的方案，存在一个连接数的阈值，并不是异步库一定就性能优势，异步库的优势主要是降低内存占用、超大并发情况下的优势，单就10k，可能标准库的响应速度更快，因为数据的读取、解析没有断层、都是单协程内完成的、同一段buffer也可以复用很多次。单就内存优化来讲，比如内存池：
> fasthttp等项目开了个pool的好头，但是对于异步网络库高度定制内存管理等场景，不够通用。
> 标准库方案的那种一个连接一个协程，就单个连接而言，在内存管理、pool定制上比异步库更方便，buffer多是在单个协程内、处理完一个消息后才会进行下一轮ReadMessage，所以内存管理更可控，异步库内存生命周期管理起来比一个连接一个协程麻烦太多了。
> 简单定制的tcp、固定header 那种要省力得多，tls/http/websocket解析起来太麻烦了，跨协议栈不同层之间的数据传递和cache，尤其是慢连接，比如测试解析逻辑时一个字节一个字节发送，再加上可能跨协程的buffer传递，还有解析到一个协议包后之前整段buffer的分割之后还需要粘包和cache等问题，结合2^N的pool的方案在应对慢连接时大部分性能都消耗在内存的使用上了，反倒性能不好。所以最近把http/websocket的内存池改了，不在使用的2^N对齐的buffer，换成无固定长度buffer的方式了，不保证一对一的分配和释放，只是尽量在各个协议层复用pool中的buffer

哈哈，我担心你介意中文，所以就凑合着用英文表达了！
nbio的底层网络包，内存管理这样 我也觉得够用了，但这个项目已经不是仅仅满足网络层了，开始搞应用层，特别是http 协议数据与请求体数据解析，如果我要基于此在实现各种插件，用到的各种自定义类型 用pool 还是觉得有点力弱了些，一定程度上能降低GC,但还是欠缺了些

**Comment by lesismal** [comment]
作了下测试，10w连接数，10000并发，这个 PR 在我的测试机器上没有带来明确的性能提升。

**Comment by lesismal** [comment]
> nbio的底层网络包，内存管理这样 我也觉得够用了，但这个项目已经不是仅仅满足网络层了，开始搞应用层，特别是http 协议数据与请求体数据解析，如果我要基于此在实现各种插件，用到的各种自定义类型 用pool 还是觉得有点力弱了些，一定程度上能降低GC,但还是欠缺了些

对于 go ，通用类型的 pool 不太现实。毕竟不像 c/c++ 那样可以 type *p = (type*)pbuf; 1.17的泛型我还没有去了解，但应该也无法实现这种类似的通用。如果全部用 unsafe 去搞了，则是引入了更多的不确定性，后续的代码都需要谨小慎微。

另外，不是所有对象都能通过 pool 管理的，比如 nbio.Conn，因为不像标准库和fasthttp那种一个连接一个协程，连接关闭协程即可退出并清理。nbio网络层连接close了，但业务协程池可能仍然持有该连接相关的handler在队列中，如果网络层 release 了这个连接，业务层执行到它时，这个连接可能刚好被重新取出用于持有新的连接，然后两个协程同时操作，dirty memory了，一切后果不可预料了，如果改成增加应用层接口然后由用户主动释放，那太不优雅了。并且，小对象的回收效率还算可以，connection 这种比起 request/response 还算是低频分配释放的了，还是可以容忍。

**Comment by sunvim** [comment]
> 作了下测试，10w连接数，10000并发，这个 PR 在我的测试机器上没有带来明确的性能提升。

嗯， 可能这级别业务少了些，但这个pr 我认为是合理的，但事件数量还是得有一个上限， 这个上限 根据我现在拍脑袋的想法，依据后续的任务池工作者的数量，保持一个魔数合适比例，甚至在网络报处理的时候 能标记那个连接数据需要优先处理等场景还是有用的，诸如此类的场景是需要在下一个读取事件轮回，应该一次性读取所有事件

**Comment by lesismal** [comment]
image

搜了下，如果是按这个概念，应该不适合你想要做的针对通用应用层场景的。这种跟一整块固定内存池是类似的，有它局限的使用场景。比如一帧或者一段时间内的固定内存需求，可以整体分配、整体释放的场景。通用业务比这个复杂得多，每个连接、每个请求都是不能明确释放时机的。所以，少年，不要浪费时间了。

nbio这里有一个固定的buffer用于定位 conn：
https://github.com/lesismal/nbio/blob/master/gopher.go#L106

但是没有用 []Conn，结构体数组故需要重复分配释放对象，但是没有这样用，而是用 []*Conn，因为我们无法确定业务层何时不再持有这个 Conn，与我上一楼说的类似，会存在 dirty 的问题。

**Comment by lesismal** [comment]
> > 作了下测试，10w连接数，10000并发，这个 PR 在我的测试机器上没有带来明确的性能提升。
> 
> 嗯， 可能这级别业务少了些，但这个pr 我认为是合理的，但事件数量还是得有一个上限， 这个上限 根据我现在拍脑袋的想法，依据后续的任务池工作者的数量，保持一个魔数合适比例，甚至在网络报处理的时候 能标记那个连接数据需要优先处理等场景还是有用的，诸如此类的场景是需要在下一个读取事件轮回，应该一次性读取所有事件

size确实是不适合太大，太大了单次 epoll_wait syscall 的内核操作时间久一点也未必划算，1024是个比较均衡的数字了，所以这个 PR 不会合并，除非能够明确证明带来性能提升。

**Comment by sunvim** [comment]
> > nbio的底层网络包，内存管理这样 我也觉得够用了，但这个项目已经不是仅仅满足网络层了，开始搞应用层，特别是http 协议数据与请求体数据解析，如果我要基于此在实现各种插件，用到的各种自定义类型 用pool 还是觉得有点力弱了些，一定程度上能降低GC,但还是欠缺了些
> 
> 对于 go ，通用类型的 pool 不太现实。毕竟不像 c/c++ 那样可以 type _p = (type_)pbuf; 1.17的泛型我还没有去了解，但应该也无法实现这种类似的通用。如果全部用 unsafe 去搞了，则是引入了更多的不确定性，后续的代码都需要谨小慎微。
> 
> 另外，不是所有对象都能通过 pool 管理的，比如 nbio.Conn，因为不像标准库和fasthttp那种一个连接一个协程，连接关闭协程即可退出并清理。nbio网络层连接close了，但业务协程池可能仍然持有该连接相关的handler在队列中，如果网络层 release 了这个连接，业务层执行到它时，这个连接可能刚好被重新取出用于持有新的连接，然后两个协程同时操作，dirty memory了，一切后果不可预料了，如果改成增加应用层接口然后由用户主动释放，那太不优雅了。并且，小对象的回收效率还算可以，connection 这种比起 request/response 还算是低频分配释放的了，还是可以容忍。

有道理，不过意见保留， 我在着手实现这个玩意， 看看效果如何，光说不练，不行，我想应该高强度业务场景下能保持 内存压力稳定，gc 稳定， 这个是我有此想法的动机

**Comment by sunvim** [comment]
> > > 作了下测试，10w连接数，10000并发，这个 PR 在我的测试机器上没有带来明确的性能提升。
> > 
> > 
> > 嗯， 可能这级别业务少了些，但这个pr 我认为是合理的，但事件数量还是得有一个上限， 这个上限 根据我现在拍脑袋的想法，依据后续的任务池工作者的数量，保持一个魔数合适比例，甚至在网络报处理的时候 能标记那个连接数据需要优先处理等场景还是有用的，诸如此类的场景是需要在下一个读取事件轮回，应该一次性读取所有事件
> 
> size确实是不适合太大，太大了单次 epoll_wait syscall 的内核操作时间久一点也未必划算，1024是个比较均衡的数字了，所以这个 PR 不会合并，除非能够明确证明带来性能提升。

么事，是一个无关紧要的pr, 主要还是看需求了

**Comment by lesismal** [comment]
很多 pool 的方案我也都尝试过，固定size的，大段中的子区间来减少 gc 的，这个线性分配器，非通用的 pool 方案，都是存在使用场景的局限，还有这几年流行的 ECS 架构的，很多减少碎片或者尽量批次的方式来优化，要么场景局限、要么需要额外的不便利，实际场景咱们具体情况具体分析

**Comment by lesismal** [comment]
> > > > 作了下测试，10w连接数，10000并发，这个 PR 在我的测试机器上没有带来明确的性能提升。
> > > 
> > > 
> > > 嗯， 可能这级别业务少了些，但这个pr 我认为是合理的，但事件数量还是得有一个上限， 这个上限 根据我现在拍脑袋的想法，依据后续的任务池工作者的数量，保持一个魔数合适比例，甚至在网络报处理的时候 能标记那个连接数据需要优先处理等场景还是有用的，诸如此类的场景是需要在下一个读取事件轮回，应该一次性读取所有事件
> > 
> > 
> > size确实是不适合太大，太大了单次 epoll_wait syscall 的内核操作时间久一点也未必划算，1024是个比较均衡的数字了，所以这个 PR 不会合并，除非能够明确证明带来性能提升。
> 
> 么事，是一个无关紧要的pr, 主要还是看需求了

好的，感谢来 PR，欢迎继续来搞 😄

**Comment by lesismal** [comment]
> > > nbio的底层网络包，内存管理这样 我也觉得够用了，但这个项目已经不是仅仅满足网络层了，开始搞应用层，特别是http 协议数据与请求体数据解析，如果我要基于此在实现各种插件，用到的各种自定义类型 用pool 还是觉得有点力弱了些，一定程度上能降低GC,但还是欠缺了些
> > 
> > 
> > 对于 go ，通用类型的 pool 不太现实。毕竟不像 c/c++ 那样可以 type _p = (type_)pbuf; 1.17的泛型我还没有去了解，但应该也无法实现这种类似的通用。如果全部用 unsafe 去搞了，则是引入了更多的不确定性，后续的代码都需要谨小慎微。
> > 另外，不是所有对象都能通过 pool 管理的，比如 nbio.Conn，因为不像标准库和fasthttp那种一个连接一个协程，连接关闭协程即可退出并清理。nbio网络层连接close了，但业务协程池可能仍然持有该连接相关的handler在队列中，如果网络层 release 了这个连接，业务层执行到它时，这个连接可能刚好被重新取出用于持有新的连接，然后两个协程同时操作，dirty memory了，一切后果不可预料了，如果改成增加应用层接口然后由用户主动释放，那太不优雅了。并且，小对象的回收效率还算可以，connection 这种比起 request/response 还算是低频分配释放的了，还是可以容忍。
> 
> 有道理，不过意见保留， 我在着手实现这个玩意， 看看效果如何，光说不练，不行，我想应该高强度业务场景下能保持 内存压力稳定，gc 稳定， 这个是我有此想法的动机

可以，不管成败，尝试一下能得到更多细节上的收获，加油。

**Pull request closed without merging**
