### PR TITLE
possible fix

### PR DESCRIPTION
**Pull request by acgreek**
This fixes the tests. Not sure if it is correct. I will merge it for now since with out this, master is clearly broken

### CODE REVIEW

**Comment by lesismal** [comment]
what's the problem?
this commit seems to waste tlsConn.Read one more time

**Comment by acgreek** [comment]
The TCP read buffer has more data, and the TLSConn and Websocket reads stop reading have consuming one frame from the TCP buffer

**Comment by lesismal** [comment]
> The TCP read buffer has more data, and the TLSConn and Websocket reads stop reading after consuming one frame from the TCP buffer

how to reproduce this problem?

I just tried this test:
https://github.com/lesismal/nbio/blob/master/examples/websocket/test_websocket/websocket_test.go

and got:
```sh
$GOPATH/github.com/lesismal/nbio/examples/websocket/test_websocket$ go test -v
=== RUN   TestWebsocketTwoRead
2021/05/21 21:32:36 done sleep
2021/05/21 21:32:36 connecting to ws://localhost:28003/ws
2021/05/21 21:32:36 dial:dial tcp [::1]:28003: connect: connection refused
exit status 1
FAIL    github.com/lesismal/nbio/examples/websocket/test_websocket      0.006s
```

time.Sleep(time.Second) would fix this:
https://github.com/lesismal/nbio/blob/master/examples/websocket/test_websocket/websocket_test.go#L102

**Comment by acgreek** [comment]
right, I guess my computer is fast enough to start the server in time for the connect.

**Comment by acgreek** [comment]
non-tls doesn't appear appear to exhibit the problem

**Comment by lesismal** [comment]
> non-tls doesn't appear appear to exhibit the problem

I think it's not the reason. I have pr for your new example, just try it: f8defd3fbd02339e8f04720597ba6fe25df28ab9

**Comment by acgreek** [comment]
sorry, it is still hanging for me. I  ctrl-c out of it 
```
$ git log |head -1 
commit f8defd3fbd02339e8f04720597ba6fe25df28ab9
$ go test -v . 
=== RUN   TestWebsocketTwoRead
2021/05/21 09:58:39.750 [INF] Gopher[NB] start listen on: ["localhost:28003"]
2021/05/21 09:58:40 done sleep
2021/05/21 09:58:40 connecting to wss://localhost:28003/wss
OnOpen: 127.0.0.1:51553
2021/05/21 09:58:40 write: hello world 0
2021/05/21 09:58:40 write: hello world 1
2021/05/21 09:58:40 write: hello world 2
2021/05/21 09:58:40 write: hello world 3
2021/05/21 09:58:40 write: hello world 4
2021/05/21 09:58:40 write: hello world 5
2021/05/21 09:58:40 write: hello world 6
2021/05/21 09:58:40 write: hello world 7
2021/05/21 09:58:40 write: hello world 8
2021/05/21 09:58:40 write: hello world 9
OnMessage: 1 hello world 1
OnMessage: 1 hello world 0
OnMessage: 1 hello world 2
OnMessage: 1 hello world 3


^CFAIL  github.com/lesismal/nbio/examples/websocket_tls/test_tls_websocket      8.325s
```

**Comment by lesismal** [comment]
the default message executor is a [MixedPool](https://github.com/lesismal/nbio/blob/master/taskpool/mixedpool.go#L15), and most of the message will handled in different goroutines, so the count++ should use atomic.Add...

if you want all the messages of one connection handled in the same goroutine(different connections could be dispatched to different goroutines), you can custom yourself's goroutine pool, for example:

```golang
emptyExecutor := func(f func()) { f() }
svr = nbhttp.NewServer(nbhttp.Config{
	Network: "tcp",
	Addrs:   []string{*addr},
}, mux, emptyExecutor)
```

```golang
messageExecutorPool = taskpool.NewFixedPool(runtime.NumCPU()*64, 1024)
```

```golang
wsConn.OnMessage(func(c *websocket.Conn, messageType int8, data []byte) {
	nbconn := c.Conn.(*nbio.Conn)
	messageExecutorPool.GoByIndex(nbconn.Hash(), func() {
		fmt.Println("OnMessage:", messageType, string(data))
		if int(atomic.AddInt32(&count, 1)) == maxCount {
			cancelFunc()
		}
		c.SetReadDeadline(time.Now().Add(time.Second * 60))
	})
})
```

then, all the messages of the same connection will be handled in order and in the same goroutine

**Comment by lesismal** [comment]
> sorry, it is still hanging for me. I ctrl-c out of it
> 
> ```
> $ git log |head -1 
> commit f8defd3fbd02339e8f04720597ba6fe25df28ab9
> $ go test -v . 
> === RUN   TestWebsocketTwoRead
> 2021/05/21 09:58:39.750 [INF] Gopher[NB] start listen on: ["localhost:28003"]
> 2021/05/21 09:58:40 done sleep
> 2021/05/21 09:58:40 connecting to wss://localhost:28003/wss
> OnOpen: 127.0.0.1:51553
> 2021/05/21 09:58:40 write: hello world 0
> 2021/05/21 09:58:40 write: hello world 1
> 2021/05/21 09:58:40 write: hello world 2
> 2021/05/21 09:58:40 write: hello world 3
> 2021/05/21 09:58:40 write: hello world 4
> 2021/05/21 09:58:40 write: hello world 5
> 2021/05/21 09:58:40 write: hello world 6
> 2021/05/21 09:58:40 write: hello world 7
> 2021/05/21 09:58:40 write: hello world 8
> 2021/05/21 09:58:40 write: hello world 9
> OnMessage: 1 hello world 1
> OnMessage: 1 hello world 0
> OnMessage: 1 hello world 2
> OnMessage: 1 hello world 3
> 
> 
> ^CFAIL  github.com/lesismal/nbio/examples/websocket_tls/test_tls_websocket      8.325s
> ```

well, yes, I got this either, but sometimes it success.
ok, merge this.

**Comment by acgreek** [comment]
I know this. I was going off the OnMessage output. I quickly hacked these tests to reproduce the problem. Cleanup later

> the default message executor is a [MixedPool](https://github.com/lesismal/nbio/blob/master/taskpool/mixedpool.go#L15), and most of the message will handled in different goroutines, so the count++ should use atomic.Add...
> 
> if you want all the messages of one connection handled in the same goroutine(different connections could be dispatched to different goroutines), you can custom yourself's goroutine pool, for example:
> 
> ```go
> emptyExecutor := func(f func()) { f() }
> svr = nbhttp.NewServer(nbhttp.Config{
> 	Network: "tcp",
> 	Addrs:   []string{*addr},
> }, mux, emptyExecutor)
> ```
> 
> ```go
> messageExecutorPool = taskpool.NewFixedPool(runtime.NumCPU()*64, 1024)
> ```
> 
> ```go
> wsConn.OnMessage(func(c *websocket.Conn, messageType int8, data []byte) {
> 	nbconn := c.Conn.(*nbio.Conn)
> 	messageExecutorPool.GoByIndex(nbconn.Hash(), func() {
> 		fmt.Println("OnMessage:", messageType, string(data))
> 		if int(atomic.AddInt32(&count, 1)) == maxCount {
> 			cancelFunc()
> 		}
> 		c.SetReadDeadline(time.Now().Add(time.Second * 60))
> 	})
> })
> ```
> 
> then, all the messages of the same connection will be handled in order and in the same goroutine

**Comment by lesismal** [comment]
> The TCP read buffer has more data, and the TLSConn and Websocket reads stop reading after consuming one frame from the TCP buffer

yes, you are right!

I check the tls code:
[here](https://github.com/lesismal/llib/blob/master/std/crypto/tls/conn.go#L1352) read just one tls encrypted packet a time, then break [this loop](https://github.com/lesismal/llib/blob/master/std/crypto/tls/conn.go#L1351), if there are more then one tls encrypted packets in the tcp recv queue, my old version of `if n < len(buffer)` will failed.

nice job, thanks!

**Comment by acgreek** [comment]
I there a better way to determine if there is more data than reading until 0 is returned? This was just a quick solution that I threw up that works around it. maybe ReadRecord can also return a bool saying if there is more data available and Read could return that?

**Comment by lesismal** [comment]
> I there a better way to determine if there is more data than reading until 0 is returned? This was just a quick solution that I threw up that works around it. maybe ReadRecord can also return a bool saying if there is more data available and Read could return that?

Yes you are right! Or we could change it here:
```
for c.input.Len() == 0 { // hi there
	if err := c.readRecord(); err != nil {
		if c.isNonBlock && err == errDataNotEnough {
			return 0, nil
		}
		return 0, err
	}
	for c.hand.Len() > 0 {
		if err := c.handlePostHandshakeMessage(); err != nil {
			if c.isNonBlock && err == errDataNotEnough {
				return 0, nil
			}
			return 0, err
		}
	}
}
```
to 
```
for {  // hi there
	if err := c.readRecord(); err != nil {
		if c.isNonBlock && err == errDataNotEnough {
			return 0, nil
		}
		return 0, err
	}
	for c.hand.Len() > 0 {
		if err := c.handlePostHandshakeMessage(); err != nil {
			if c.isNonBlock && err == errDataNotEnough {
				return 0, nil
			}
			return 0, err
		}
	}
}
```

And my pre version of `if n < len(buffer)` would work.

**Comment by lesismal** [comment]
And I have just make a new branch changing the messageExecutor type to `func(index int, f func())` which is a little better convenient to custom goroutines pool:
https://github.com/lesismal/nbio/tree/messageExecutor

**Comment by lesismal** [comment]
I also invite you to become the collaborator of llib, you can merge the pull requests to nbio/llib/arpc yourself if you need.
Make yourself at home.

**Comment by lesismal** [comment]
> ```
> for c.input.Len() == 0 { // hi there
> 	if err := c.readRecord(); err != nil {
> 		if c.isNonBlock && err == errDataNotEnough {
> 			return 0, nil
> 		}
> 		return 0, err
> 	}
> 	for c.hand.Len() > 0 {
> 		if err := c.handlePostHandshakeMessage(); err != nil {
> 			if c.isNonBlock && err == errDataNotEnough {
> 				return 0, nil
> 			}
> 			return 0, err
> 		}
> 	}
> }
> ```
> 
> to
> 
> ```
> for {  // hi there
> 	if err := c.readRecord(); err != nil {
> 		if c.isNonBlock && err == errDataNotEnough {
> 			return 0, nil
> 		}
> 		return 0, err
> 	}
> 	for c.hand.Len() > 0 {
> 		if err := c.handlePostHandshakeMessage(); err != nil {
> 			if c.isNonBlock && err == errDataNotEnough {
> 				return 0, nil
> 			}
> 			return 0, err
> 		}
> 	}
> }
> ```

this doesn't work, need more work.

**Comment by lesismal** [comment]
> I there a better way to determine if there is more data than reading until 0 is returned? This was just a quick solution that I threw up that works around it. maybe ReadRecord can also return a bool saying if there is more data available and Read could return that?

Do you mean return with ` err == errDataNotEnough`? anyway, worth trying!

**Pull request merged**
