### PR TITLE
support tls certificates update

### PR DESCRIPTION
**Pull request by sunvim**
as the title said

### CODE REVIEW

**Comment by lesismal** [comment]
published: [v1.2.2](https://github.com/lesismal/nbio/releases/tag/v1.2.2)

**Comment by sunvim** [comment]
> published: [v1.2.2](https://github.com/lesismal/nbio/releases/tag/v1.2.2)

thanks, can u create a slack channel, i think it's usefull for this project, to developers communicate each other convenietly

**Comment by lesismal** [comment]
> > published: [v1.2.2](https://github.com/lesismal/nbio/releases/tag/v1.2.2)
> 
> thanks, can u create a slack channel, i think it's usefull for this project, to developers communicate each other convenietly

新建了个，试下可以不：
https://arpcnbio.slack.com/archives/C02EHQU6T33

**Comment by sunvim** [comment]
> > > published: [v1.2.2](https://github.com/lesismal/nbio/releases/tag/v1.2.2)
> > 
> > 
> > thanks, can u create a slack channel, i think it's usefull for this project, to developers communicate each other convenietly
> 
> 新建了个，试下可以不：
> https://arpcnbio.slack.com/archives/C02EBCTCWSG

不行，此工作区没有账户，你有什么喜欢的沟通方式不，方便沟通

**Comment by sunvim** [comment]
我的邮箱是： sunsc0220@gmail.com

**Comment by lesismal** [comment]
> 我的邮箱是： [sunsc0220@gmail.com](mailto:sunsc0220@gmail.com)

添加了，看下有了没

**Comment by lesismal** [comment]
或者试下这个可以不：
https://join.slack.com/t/arpcnbio/shared_invite/zt-vh3g1z2v-qqoDp1hQ45fJZqwPrSz4~Q

**Pull request merged**
