### PR TITLE
Websocketpp example

### PR DESCRIPTION
**Pull request by acgreek**
The websocketpp client connects to the websocket tls server but doesn't complete the tls handshake. For reference, I confirmed the websocketpp client is able to connect and send data to wss://echo.websocket.org

### CODE REVIEW

**Comment by lesismal** [comment]
so it is all right with llib 1.0.0?

**Comment by acgreek** [comment]
No, a have a developer still having issues with websocketpp/asio; the
stream comes in corrupt. I haven't been able to reproduce with my simple
example yet and am busy today.

**Comment by lesismal** [comment]
I reproduced this bug with your [cpp example](https://github.com/lesismal/nbio/pull/22/commits/63990b08b2ca424aabc0928686dd6bcb9d62d164#diff-675f5b4f2916ccfe3f282046dbfa792fb10cc6446ef578c31f3bf7c5edb710bc).

[this commit](https://github.com/lesismal/nbio/commit/9ebb7167bfb366bac4b1a822cdd64fd347d635a7) works fine now, please try it.

**Comment by acgreek** [comment]
wow thanks, I didn't want to trouble you until I was certain. I'm think the problem was with websocketpp on linux as opposed to macos as it my personal developer laptop; the developer who reported issue is using linux. Is that the case; did you confirm the problem with linux?

**Comment by lesismal** [comment]
> wow thanks, I didn't want to trouble you until I was certain. I'm think the problem was with websocketpp on linux as opposed to macos as it my personal developer laptop; the developer who reported issue is using linux. Is that the case; did you confirm the problem with linux?

This is a half-frame-parsing bug, and all platforms should be affected. 

The TLSConn uses [the same buffer](https://github.com/lesismal/nbio/blob/master/nbhttp/server.go#L508) to read data, then passes the buffer to websocket.Upgrader to parse frame/message.
When there's only a half-frame, the upgrader will cache the buffer, it should make a copy of the buffer if needed, but there's a bug for the copying logic and the upgrader does not copy it.
When the Conn.Read next time, the buffer is overwritten which makes the upgrader's cache dirty, then everything goes wrong.

Thank you for pointing out this bug!

Please continue to monitor your service, if no more problems are found, we could release v1.0.3.

**Comment by acgreek** [comment]
yes, developer confirmed this worked. Thank you so much

**Comment by lesismal** [comment]
> yes, developer confirmed this worked. Thank you so much

my pleasure, you are welcome

**Pull request merged**
